import Board from "../models/Board.js";

export async function createBoard(req, res) {
  try {
    const board = new Board(); // no _id specified, auto-generated by MongoDB
    const savedBoard = await board.save();
    res.status(201).json(savedBoard); // returns board with generated _id
  } catch (error) {
    console.error("Error creating board:", error);
    res.status(500).json({ message: "Internal server error" });
  }
}
